### ISSUE TITLE
Remove redundant flags

### ISSUE THREAD

**Issue by durkie** [PublicDesignWorkshop/FoodParent#1]
Instead of:

``` sql
INSERT INTO `flag` (`id`, `name`) VALUES
(1, 'dead'),
(2, 'cut down'),
(3, 'verfied'),
(4, 'hidden'),
(5, 'growing');
```

``` sql
INSERT INTO `flag` (`id`, `name`) VALUES
(1, 'dead'),
(2, 'verified'),
(3, 'hidden');
```

is fine (if something is "`cut down`" then it's also "`dead`", so "`cut down`" can be removed. Also, if something is "`growing`", then it's not "`dead`", so "`growing`" can be removed)

**Comment by ThePlushEater** [comment]
I removed the unnecessary flags as you mentioned.
